config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index' 
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
  get 'feed', to: "posts#feed"

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
          resources :likes, only: [:index, :create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attribute :role, default: 'user'
  # Associations
  has_many :posts, class_name: 'Post', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'author_id', dependent: :destroy

  # Default attributes
  attribute :posts_counter, default: 0

  # validations of Records
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # displaying last three Posts made by user
  def last_three
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(updated_at: :asc)
  end

  def show
    @user = User.includes(:posts).find(params[:id])
    @current_user = current_user
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_badge.html.erb
<%= link_to user_path(user), class: 'badge user-badge bg-dark rounded d-flex align-items-center gap-2 text-decoration-none' do %>
  <div class="d-grid place-items-center">
    <%= image_tag(
      "#{user.photo}",
      alt: "#{user.name}-img",
      class: "badge-image rounded-circle"
    ) %>
  </div>
  <strong class='fs-5'><%= user.name %></strong>
<% end %>

app/views/users/_user_card.html.erb
<div class="container mb-2 p-0 rounded border">
  <%= link_to user_path(user), class: "user-detail p-0 w-100 text-decoration-none", id: "user-card" do %>
    <div class="row p-lg-0">
      <div class="col-lg-3 col-md-3 col-sm-12">
        <%= image_tag(
          "#{user.photo}",
          alt: "#{user.name}-img",
          class: "user-image p-0 img-thumbnail w-100"
        ) %>
      </div>
      <div
        class="
          col-lg-9
          col-md-9
          col-sm-12
          d-flex
          flex-column
          justify-content-center
          p-3
        "
      >
        <h3 class="user-name align-self-start"><%= user.name %></h3>
        <% if user.posts_counter == 0 %>
          <span class="align-self-end d-block">No Post 📪 Yet</span>
        <% else %>
          <span class="align-self-end d-block"><%= user.name %>
            has
            <strong><%= user.posts_counter %></strong>
            posts</span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% if @users == nil %>
  <p>No user added yet</p>
<% else %>
  <%= render "layouts/title",
  title: "Our Blog App has #{User.count} Users and counting!" %>
  <div class="text-end">
  </div>
  <div class="user user-shelf">
    <% @users.each do |user| %>
      <%= render "user_card", user: user %>
    <% end %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= render 'user_card', user: @user %>


<% if @current_user && @current_user.id == @user.id %>
  <div class='d-flex align-items-center m-5 justify-content-around'>
    <%= link_to "New Post",  new_user_post_path(@current_user), class: 'badge bg-primary text-decoration-none fs-2 text-light' %> 
    <%= link_to "Edit Account", edit_user_registration_path, class: 'badge bg-info text-decoration-none fs-2 text-light' %>  
<button type="button" class="badge bg-danger text-decoration-none fs-2 text-light" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Delete Account
</button>
</div>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you Sure 🥲🥲</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h3>We Feel bad to let you go</h2>
        <p>Is this your Final Decision 🔥</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= button_to "Delete my account", registration_path(@current_user), method: :delete, class:"btn btn-danger" %>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="card">
  <div class="card-header bg-dark text-light">
    <h2>Bio</h2>
  </div>
  <div class="card-body bg-success text-light">
    <p class="card-text"><%= @user.bio %></p>
  </div>
</div>
<h2 class="text-center text-primary fs-1 my-5">Recent Posts 📪</h2>
<% if @user.posts.length == 0 %>
  <div class="card">
    <div class="card-header bg-dark text-light">
      <h2><%= @user.name %></h2>
    </div>
    <div class="card-body bg-success text-light">
      <p class="card-text">📪No Post yet 💕💬 But Soon in Future 🙌🙌😁</p>
    </div>
  </div>
<% else %>
  <section>
    <%= render 'posts/post_card', posts: @user.last_three, comments: false %>
  </section>
<% end %>
<div class="text-center my-5">
  <% unless @user.posts_counter == 0 %>
    <%= link_to 'See all Posts', user_posts_path(@user), class: 'btn btn-success' %>
  <% end %>
</div>