config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index' 
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
  get 'feed', to: "posts#feed"

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
          resources :likes, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Public (guest) permissions
    can :read, Post
    can :read, User
    can :read, Like
    can :read, Comment

    return unless user.present? # Only proceed if the user is authenticated

    # Permissions for authenticated users
    can %i[create destroy read edit], Post, author_id: user.id
    can %i[create destroy read], Comment, author_id: user.id

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, class_name: 'Post'

  # creation and destructionction according to comment on post
  after_create :increment_comment_on_posts
  after_destroy :decrement_comment_on_posts

  private

  # incrementor
  def increment_comment_on_posts
    post.comments_counter += 1
    post.save
  end

  # decrementor
  def decrement_comment_on_posts
    post.comments_counter -= 1
    post.save
  end
end

app/models/like.rb
class Like < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, class_name: 'Post'

  # creation and destructionction according to like on post
  after_create :increment_like_on_posts
  after_destroy :decrement_like_on_posts

  private

  # Incrementor
  def increment_like_on_posts
    post.likes_counter += 1
    post.save
  end

  # Decrementor
  def decrement_like_on_posts
    post.likes_counter -= 1
    post.save
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, class_name: 'Comment', dependent: :destroy
  has_many :likes, class_name: 'Like', dependent: :destroy
  attribute :comments_counter, default: 0
  attribute :likes_counter, default: 0

  # creation and destruction according to Post creation by user
  after_create :increment_user_posts_counter
  after_destroy :decrement_user_posts_counter

  # validation
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # display five recent comments
  def recent_five_comments
    comments.last(5)
  end

  private

  # Incrementor
  def increment_user_posts_counter
    author.posts_counter += 1
    author.save
  end

  # Decrementor
  def decrement_user_posts_counter
    author.posts_counter -= 1
    author.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attribute :role, default: 'user'
  # Associations
  has_many :posts, class_name: 'Post', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'author_id', dependent: :destroy

  # Default attributes
  attribute :posts_counter, default: 0

  # validations of Records
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # displaying last three Posts made by user
  def last_three
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :photo, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def new
    @comment = Comment.new
    @user = current_user
  end

  def create
    user = current_user
    post = Post.find(params[:post_id])
    new_comment = Comment.new(post:, author: user, text: comment_params['text'])

    if new_comment.save
      redirect_to request.referrer, notice: 'Comment created successfully!'
    else
      redirect_to request.referrer, alert: 'Comment could not be created.'
    end
  end

  private

  def comment_params
    params.require(:new_comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  def new
    @like = Like.new
    @user = current_user
  end

  def create
    user = current_user
    post = Post.find(params[:post_id])
    like = Like.new(post:, author: user)

    if like.save
      redirect_to request.referrer, notice: 'Like added successfully!'
    else
      redirect_to request.referrer, alert: 'Unable to add like.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: %i[feed show]
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: @user.id).paginate(page: params[:page], per_page: 3)
  end

  def feed
    @posts = Post.includes(:author).order(:updated_at).paginate(page: params[:page], per_page: 6)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @current_user = current_user
  end

  def new
    @post = Post.new
    @current_user = current_user
  end

  def create
    @current_user = current_user
    @post = Post.new(
      author: current_user,
      title: post_params['title'],
      text: post_params['text']
    )
    if @post.save
      redirect_to user_post_path(@current_user, @post), notice: 'Post created successfully!'
    else
      redirect_to new_user_post_path(@current_user), alert: 'Failed to create post.'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @current_user = current_user
    if @post.destroy
      redirect_to user_posts_path(@current_user), notice: 'Post was successfully destroyed.'
    else
      redirect_to user_post_path(@current_user), alert: 'Failed to destroy post.'
    end
  end

  def edit
    @post = Post.find(params[:id])
    @current_user = current_user
  end

  def update
    @post = Post.find(params[:id])
    @current_user = current_user
    if @post.update(post_params)
      redirect_to user_post_path(@current_user, @post), notice: 'Post updated successfully!'
    else
      redirect_to edit_user_post_path(@current_user, @post), alert: 'Failed to update post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(updated_at: :asc)
  end

  def show
    @user = User.includes(:posts).find(params[:id])
    @current_user = current_user
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/likes_helper.rb
module Api::V1::LikesHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = %i[hard_wrap autolink no_intra_emphasis fenced_code_blocks]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sub_title.html.erb
<div class="card-header bg-warning text-light">
  <h1 class="text-center fs-3 mb-3"><%= title %></h1>
</div>

app/views/layouts/_title.html.erb
<div class="card-header bg-success text-light">
  <h1 class="text-center pt-5 fs-1 mb-3"><%= title %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-lg-5">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <%= image_tag("logo.png", alt: "logo", width: "30px", height: "30px", class: "d-inline-block align-text-top mx-2") %>
          Blog App
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item mx-l-2">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item mx-l-2">
              <%= link_to 'Feed', feed_path, class: 'nav-link' %>
            </li>
          </ul>
          
          <% if user_signed_in? %>
            <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-success' %>
            <% else %>
            <%= button_to "Log in", user_session_path, class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </nav>
    <p class="notice position-absolute position-absolute start-50"><%= notice %></p>
    <p class="alert position-absolute position-absolute start-50"><%= alert %></p>
    <%= yield %>
    <footer class="container-fluid bg-dark d-flex justify-content-around text-light mb-0 p-3">
      <p>All Rights and ©️ Belongs to <a href="https://github.com/PowerLevel9000" class="text-decoration-none text-danger">Adarsh Pathak</a> under 
        <a class="text-decoration-none text-danger" href="https://github.com/PowerLevel9000/Blog/blob/dev/LICENSE">GNU GENERAL PUBLIC LICENSE</a>
      </p>
       <a href="https://buymeacoffee.com/adi8090808E" target="_blank"><img src="https://img.shields.io/badge/Buy%20Me%20a%20Coffee-ffdd00?style=for-the-badge&logo=buy-me-a-coffee&logoColor=black"></a>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>